name: sqlentity
description: SQLite DataBase, performs the creation of the database, manages activity control, and all the benefits of an ORM.
version: 1.0.8
author: kayque_rodrigues7@hotmail.com
homepage: https://github.com/kayque7k/sqlentity.git

environment:
  sdk: '3.3.1'

dependencies:

  flutter:
    sdk: flutter

  sqflite: ^2.3.2
  path: ^1.9.0



flutter:
  plugin:
    androidPackage: com.snacktime.sqlentity
    pluginClass: SqlentityPlugin

